service:
 message: Hello World naveen is here .......

spring:
  cloud:
    config: 
      uri : http://localhost:9001
    bus:
      enabled: true
  application:
    name: config-client
  rabbitmq:
    username: test
    password: test
    host: 192.168.169.252
    
server:
  port: 9002
  
